### ISSUE TITLE
Unable to Install on CentOS 7 (DirectAdmin)

### ISSUE THREAD

**Issue by jljr222** [absalomedia/sassphp#9]
I have sent my hosting provider a link to this repo with the instructions, but they were unable to install it successfully. They asked me to reach out for instructions on how to install this on my particular environment. I am hoping to have this be an option for compiling my scss in a custom theme module I am building. I want to be able to provide those who want to us it, clear directions.

Here is what the support tech said was returned:

> php_sass.h:25:18: fatal error: sass.h: No such file or directory

Could you tell me if this can be installed on CentOS and is there an option for Windows machines?

**Comment by absalomedia** [comment]
The SassPHP package has never had coverage in Centos or DirectAdmin, prior to my work on it or when I took it over. Coverage has been done previously for Debian. I'd welcome sponsorship to drive development towards Centos/DirectAdmin for you & others.

I've done some preliminary attempts to build Windows PHP extension but without success so far, Again due to time & limited availability for edge cases,

**Comment by jljr222** [comment]
Ah, that would explain it. Thanks for letting me know.
